// quiz/item-selection/src/js/react-version/components/editor-with-mask.jsx
import React from 'react';

import { Mask } from './mask';
import { ItemOverlay } from './item-overlay';

export const App = ({ itemGroup, mask }) => {
  return (
    <>
      {mask ? <Mask mask={mask} /> : <></>}
      {itemGroup.map((item) => (
        <ItemOverlay key={item.id} item={item}></ItemOverlay>
      ))}
    </>
  );
};

// quiz/item-selection/src/js/vue-version/components/editor-with-mask.vue
<template>
  <div>
    <Masker v-if="mask" :mask="mask"></Masker>
    <ItemOverlay v-for="item in itemGroup" :key="item.id" :item="item" />
  </div>
</template>

<script>
import Masker from "./mask.vue";
import ItemOverlay from "./item-overlay.vue";

export default {
  components: {
    Masker,
    ItemOverlay
  },
  props: ["mask", "itemGroup"]
};
</script>
