// quiz/item-selection/src/js/react-version/components/item-overlay.jsx
import React from 'react';

export const ItemOverlay = ({ item }) => {
  const {
    pos: [x, y],
    size: [w, h],
    type,
    actived,
    value,
  } = item;

  let className = 'item';
  if (actived) {
    className += ' actived';
  }

  return (
    <div
      className={className}
      style={{
        transform: `translate(${x}px, ${y}px)`,
        width: `${w}px`,
        height: `${h}px`,
      }}
      data-type={type}
    >
      <div className="el-button-mix">{value}</div>
    </div>
  );
};

// quiz/item-selection/src/js/vue-version/components/item-overlay.vue
<template>
  <div :class="className" :style="style" data-type="type">
    <div class="el-button-mix">{{item.value}}</div>
  </div>
</template>

<script>
export default {
  props: ["item"],

  computed: {
    className() {
      let className = "item";
      if (this.item.actived) {
        className += " actived";
      }
      return className;
    },
    style() {
      const {
        pos: [x, y],
        size: [w, h]
      } = this.item;

      return {
        transform: `translate(${x}px, ${y}px)`,
        width: `${w}px`,
        height: `${h}px`
      };
    }
  }
};
</script>
