// quiz/item-selection/src/js/react-version/components/mask.jsx
import React from 'react';

export const Mask = ({ mask }) => {
  const {
    pos: [x, y],
    size: [w, h],
  } = mask;
  return (
    <svg
      className="mask"
      style={{
        transform: `translate(${x}px, ${y}px)`,
        width: `${w}px`,
        height: `${h}px`,
      }}
    ></svg>
  );
};

// quiz/item-selection/src/js/vue-version/components/mask.vue
<template>
  <svg class="mask" :style="style" />
</template>

<script>
export default {
  props: ["mask"],

  computed: {
    style() {
      console.warn(this.mask);
      const {
        pos: [x, y],
        size: [w, h]
      } = this.mask;

      return {
        transform: `translate(${x}px, ${y}px)`,
        width: `${w}px`,
        height: `${h}px`
      };
    }
  }
};
</script>
